### ISSUE TITLE
demo driver page and skeleton js library

### ISSUE THREAD

**Issue by SafeSlingerProject** [SafeSlingerProject/exchange-javascript#1]
- should accept 2 fields: server and secret
- server should default to https://slinger-dev.appspot.com
- 2 fields should pass to javascript library
- library should validate 2 fields for format: server = url style, secret = not empty

**Comment by SafeSlingerProject** [comment]
Also, physical endpoints to the library:
- UIs for requesting input: number users, lowest group number, 3-word phrase.
- http POST calls to assignUser, syncCommits, syncData, syncSigs, syncNodes, syncMatch

UI: server=string, secret=string
library: server=string, secret=binary/byte-array

**Comment by mwfarb** [comment]
@shrimalmadhur The skeleton was done some time ago in your first commit, so I'm closing this one. I've added a number of issues which breaks the whole project down into smaller parts so we can track progress using milestones. 

I've created a mile stone for 2-party exchange to track phase 1 and one for multiparty tasks to track the follow up phase.
